name: Check toolbar bundle size

on:
    pull_request:
        paths: # Only run if the frontend has changed
            - 'frontend/**'
            - 'package.json'
            - '.github/workflows/toolbar-bundle-check.yml'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: preactjs/compressed-size-action@v2
              with:
                  build-script: 'build'
                  compression: 'none'
                  pattern: 'frontend/dist/toolbar.js'
